### ISSUE TITLE
issues with installation

### ISSUE THREAD

**Issue by JLiLab** [JinmiaoChenLab/GraphST#8]
Thank you for sharing the interesting method. But I had difficulties installing the package following the instruction. First of all, is there cudnn>=10.2?

Also, I got the following error: 
>>> from GraphST import GraphST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zeiss\TOOLS\GraphST\GraphST\__init__.py", line 11, in <module>
    from .utils import clustering, project_cell_to_spot
  File "C:\Users\zeiss\TOOLS\GraphST\GraphST\utils.py", line 4, in <module>
    import scanpy as sc
  File "C:\Users\zeiss\.conda\envs\GraphST\lib\site-packages\scanpy\__init__.py", line 6, in <module>
    from ._utils import check_versions
  File "C:\Users\zeiss\.conda\envs\GraphST\lib\site-packages\scanpy\_utils\__init__.py", line 21, in <module>
    from anndata import AnnData, __version__ as anndata_version
  File "C:\Users\zeiss\.conda\envs\GraphST\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData
  File "C:\Users\zeiss\.conda\envs\GraphST\lib\site-packages\anndata\_core\anndata.py", line 17, in <module>
    import h5py
  File "C:\Users\zeiss\.conda\envs\GraphST\lib\site-packages\h5py\__init__.py", line 25, in <module>
    from . import _errors
ImportError: DLL load failed while importing _errors: The specified procedure could not be found.

**Comment by JLiLab** [comment]
finally, do we need the environment.yml to create a conda environment?

**Comment by longyahui** [comment]
Hi, 

Thanks a lot for your attention on our work.

The cudnn version should be >=10.2. It looks like the error results from incompatible packages. 

It's the best to create an virtual environment to run our model. We have provided the tutorial to create virtual environment and install GraphST package. For more details, please refer to the link https://deepst-tutorials.readthedocs.io/en/latest/Installation.html.  Thank you.

Best regards,
Yahui

**Comment by JLiLab** [comment]
My bad, the answer is in the paper: "First, for two given tissue slices, we employ the algorithm PASTE57 to align their H&E images to ensure that the two slices are adjacent in space. Next, with the aligned spatial coordinates, a joint neighborhood graph for the two slices is constructed in the same way as with a single slice."

**Comment by longyahui** [comment]
Hi James,

     Correct. We used existing PASTE algorithm to align both samples. Alternatively, we can also manually align samples. Thank you.

     Best regards,
     Yahui

**Comment by ruqianl** [comment]
@JLiLab I was also confused by the package requirement:  cudnn>=10.2. Wondering which cuDNN version worked for you? Thanks
